description: Exceptions File for vet
exceptions:
  - ecosystem: pypi
    expires: "2026-05-10T00:00:00Z"
    id: 01JKMC07KAGJYEDZX1XPAC3SKP
    name: 'meme-llm'
    version: 2.4.1
    reason: "False positive - CVE doesn't apply to our usage"
