name: Dependency Scanning  
  
on:  
  pull_request:  
    branches: [ main ]  
  push:  
    branches: [ main ]  
  
permissions:  
  contents: read  
  issues: write  
  pull-requests: write  
  
jobs:  
  scan:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
        
      - name: Scan Dependencies  
        uses: safedep/vet-action@208b2ea6ad96ff373e56e6a7b22a43881ecad188
        with:
          cloud: true
          malware: true
          cloud-key: ${{ secrets.SAFEDEP_CLOUD_API_KEY }}
          cloud-tenant: ${{ secrets.SAFEDEP_CLOUD_TENANT }}
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
